import { useState } from 'react';
import { ShoppingBag, Plus, Minus, Trash2, ArrowUpRight, LockKeyhole, MessageCircle } from 'lucide-react';
import { Modal } from './Modal';
import { money, priceFor, sizeLabel, bagMessage, whatsappLink } from '../lib/atelier';

export const BagDrawer = ({ open, onClose, items, onQuantity, onRemove }) => {
  const [name,setName] = useState('');
  const [city,setCity] = useState('');
  const count = items.reduce((n,i)=>n+i.quantity,0);
  const total = items.reduce((n,i)=>n+priceFor(i.product,i.metal)*i.quantity,0);
  return <Modal open={open} onClose={onClose} title="Your private bag" className="bag-drawer" testId="bag-drawer">
    <div className="bag-heading"><span className="eyebrow">EXCEPTIONALLY YOURS</span><h2 data-testid="bag-title">Your private bag <sup>{count}</sup></h2><p>A collection of things worth keeping.</p></div>
    {!items.length ? <div className="bag-empty empty-state" data-testid="empty-bag"><ShoppingBag size={35} strokeWidth={1}/><h3>Your next heirloom awaits.</h3><p>A little room for something extraordinary.</p><button className="button button-dark" onClick={onClose} data-testid="bag-continue-shopping">Discover the collection <ArrowUpRight size={15}/></button></div> : <><div className="bag-items">{items.map(item => <article className="bag-item" key={item.key} data-testid={`bag-item-${item.key}`}><img src={item.product.image} alt={item.product.name} width="100" height="120"/><div className="bag-item-details"><h3 data-testid={`bag-item-title-${item.key}`}>{item.product.name}</h3><p data-testid={`bag-item-options-${item.key}`}>{item.metal}<br/>{sizeLabel(item.product,item.size)}</p><div className="bag-item-bottom"><div className="quantity-control"><button disabled={item.quantity===1} onClick={() => onQuantity(item.key,-1)} aria-label={`Decrease quantity of ${item.product.name}`} data-testid={`quantity-minus-${item.key}`}><Minus size={12}/></button><span data-testid={`quantity-value-${item.key}`}>{item.quantity}</span><button disabled={item.quantity>=20} onClick={() => onQuantity(item.key,1)} aria-label={`Increase quantity of ${item.product.name}`} data-testid={`quantity-plus-${item.key}`}><Plus size={12}/></button></div><strong data-testid={`bag-item-price-${item.key}`}>{money(priceFor(item.product,item.metal)*item.quantity)}</strong><button className="remove-item" onClick={() => onRemove(item.key)} aria-label={`Remove ${item.product.name}`} data-testid={`remove-item-${item.key}`}><Trash2 size={14}/></button></div></div></article>)}</div>
    <div className="bag-summary"><div className="optional-details"><label>Your name <span>(optional)</span><input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="How shall we address you?" data-testid="bag-client-name"/></label><label>City / country <span>(optional)</span><input value={city} maxLength={120} onChange={e=>setCity(e.target.value)} placeholder="Where will your story continue?" data-testid="bag-client-city"/></label></div><div className="summary-row"><span>Subtotal</span><b data-testid="bag-subtotal">{money(total)}</b></div><div className="summary-row"><span>Insured delivery</span><span className="gold-text">Complimentary</span></div><div className="summary-row"><span>Signature velvet packaging</span><span className="gold-text">Our pleasure</span></div><div className="summary-total"><span>Estimated total</span><strong data-testid="bag-total">{money(total)} <small>USD</small></strong></div><a className="button button-dark full-width" href={whatsappLink(bagMessage(items,name,city))} target="_blank" rel="noopener noreferrer" data-testid="bag-checkout-whatsapp"><MessageCircle size={17}/>Order bag via WhatsApp<ArrowUpRight size={16}/></a><p className="bag-reassurance" data-testid="bag-reassurance"><LockKeyhole size={15}/><span>No payment is taken now. Your dedicated concierge will confirm availability, sizing, certification and payment arrangements.</span></p></div></>}
  </Modal>;
};