import { ArrowUpRight, MessageCircle, BadgeCheck, Star } from 'lucide-react';
import { Chapter, Reveal, Crest } from './Brand';
import { bespokeLink } from '../lib/atelier';

export const Editorial = () => <>
  <div className="editorial-marquee" aria-label="Not made for a moment. Made for a lifetime."><div className="marquee-track" aria-hidden="true">{[1,2,3,4].map(i=><span key={i}>Not made for a moment. <em>Made for a lifetime.</em><Crest/></span>)}</div></div>
  <section className="maison-section" id="maison" data-testid="maison-section"><div className="maison-layout page-width"><Reveal className="maison-visual"><img src="https://images.unsplash.com/photo-1742627032795-1dfb552448ce?auto=format&fit=crop&w=1000&q=85" alt="An intricate heritage necklace set with rubies, emeralds and diamonds, displayed on black velvet" loading="lazy" width="800" height="1000"/><div className="maison-photo-label"><span>THE ROYAL HERITAGE COLLECTION</span><p>Patience, made precious.</p></div><div className="maison-corner">V.</div></Reveal><Reveal className="maison-copy" delay={.15}><Chapter number="02">THE SOUL OF THE MAISON</Chapter><h2 data-testid="maison-heading">Some legacies<br/>aren’t written.<br/><em>They’re worn.</em></h2><p>Where imperial goldsmithing meets contemporary haute joaillerie. We don’t simply create jewelry. We give your most precious moments a form that lasts forever.</p><div className="manifesto-list">{[['I','Nature’s rarest. Nothing less.','Every stone, hand-selected for its cut, clarity, and unmistakable inner fire.'],['II','Human hands. Extraordinary devotion.','Master artisans, decades of savoir-faire, and no shortcuts. Ever.'],['III','An arrival worth remembering.','Our signature velvet casket. Your certificate of authenticity. A new chapter.']].map(([num,title,text])=><div className="manifesto-item" key={num} data-testid={`manifesto-${num}`}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><a href={bespokeLink} target="_blank" rel="noopener noreferrer" className="maison-link" data-testid="maison-atelier-link">Step inside our atelier <ArrowUpRight size={17}/></a></Reveal></div></section>
</>;

export const Reviews = () => <section className="reviews-section section-space page-width" id="client-diary"><Reveal><Chapter number="04">THE STORIES THAT STAY WITH US</Chapter><div className="section-heading"><h2>Precious pieces.<br/><em>Even more precious stories.</em></h2><div className="review-overall" data-testid="reviews-overall"><div>★★★★★</div><span><b>4.9 / 5</b> from 2,400+ connoisseurs</span></div></div></Reveal><div className="reviews-grid">{[{name:'Eleanor V.',location:'ZURICH, SWITZERLAND',initial:'EV',quote:'“For our tenth anniversary, a piece that felt like our very first promise. The concierge understood exactly what we were looking for. Unmatched service, extraordinary craftsmanship.”',piece:'Floral Diamond Blossom Ring'},{name:'Aarav M.',location:'MUMBAI, INDIA',initial:'AM',quote:'“The craftsmanship is mesmerizing. The gold has a beautiful weight to it, and the diamonds catch the light from across the room. It feels like a piece of our family’s future.”',piece:'Crossed Hearts Diamond Pendant'},{name:'Isabella R.',location:'NEW YORK, USA',initial:'IR',quote:'“From a conversation to a velvet box at my door. Every detail was considered. I’ve never felt so personally looked after. This is what luxury should feel like.”',piece:'Duchess Brilliant Tennis Bracelet'}].map((r,i)=><Reveal className="review-card" key={r.name} delay={i*.1} data-testid={`review-card-${i}`}><div className="review-card-top"><div className="review-stars">{[1,2,3,4,5].map(n=><Star size={11} key={n} fill="currentColor"/>)}</div><BadgeCheck size={17} strokeWidth={1.2}/></div><blockquote>{r.quote}</blockquote><div className="reviewer"><span className="reviewer-initials">{r.initial}</span><div><strong>{r.name}<BadgeCheck size={11}/></strong><small>{r.location}</small></div></div><p className="review-piece">{r.piece}</p></Reveal>)}</div></section>;

export const Concierge = () => <section className="concierge-section page-width" id="concierge" data-testid="bespoke-section"><Reveal className="concierge-panel"><div className="concierge-ornament" aria-hidden="true"><Crest/></div><div className="concierge-copy"><span className="eyebrow"><span className="online-dot"/>YOUR VISION. OUR SAVOIR-FAIRE.</span><h2>Something only <em>you</em><br/>could have imagined.</h2><p>A once-in-a-lifetime ring. A bridal heirloom. A little idea, made extraordinary.<br/>Let’s create the piece that could only be yours.</p></div><div className="concierge-actions"><a href={bespokeLink} target="_blank" rel="noopener noreferrer" className="button button-dark" data-testid="bespoke-whatsapp-link"><MessageCircle size={17}/>Begin a personal conversation<ArrowUpRight size={16}/></a><span>NO FORMS. NO WAITING LISTS. JUST YOU & YOUR ATELIER.</span></div></Reveal></section>;