import { ArrowUpRight } from 'lucide-react';
import { Modal } from './Modal';
import { consultationLink } from '../lib/atelier';

const content = {
  care: { title:'Treasured. For generations.', eyebrow:'CARE & KEEPING', paragraphs:['Keep your creation in its own soft pouch or velvet-lined compartment, away from other pieces to prevent scratches. Remove jewelry before swimming, exercising, and applying perfume or skincare.', 'Clean gold and diamonds gently with lukewarm water, a drop of mild soap, and a soft brush. Rinse carefully and pat dry. Pearls, emeralds and treated gemstones need specialist care; avoid ultrasonic cleaners.', 'Your concierge can advise on professional inspections, prong checks, cleaning and resizing. The right care keeps your heirloom luminous for years to come.'] },
  delivery:{title:'An exceptional arrival.',eyebrow:'DELIVERY & RETURNS',paragraphs:['Your concierge confirms availability, the delivery destination, any import duties and the delivery timeline before you make payment. Insured delivery and our signature velvet packaging are included in the quoted collection price.', 'A 30-day return window is offered for eligible, unworn collection pieces with their certificates and original packaging. Bespoke, engraved and resized pieces may have different eligibility; please confirm the written terms with your concierge before ordering.', 'To arrange a return or discuss an existing delivery, contact the atelier with your order reference. Do not dispatch precious jewelry without the insured return instructions.']},
  privacy:{title:'Discretion, by design.',eyebrow:'YOUR PRIVACY',paragraphs:['No account is required to explore VELARO. Your bag and saved creations are stored in this browser so they remain here for your next visit. You can remove saved items at any time.', 'Joining the Collector’s Circle stores your email address and consent in our subscriber database. We use those details for collection communications. To request removal, email concierge@velarojewels.com.', 'WhatsApp inquiries open an external service with your selected product details. Optional client name and delivery city are included only if you enter them. WhatsApp’s own privacy terms apply. No payment details are collected by this website.']},
  terms:{title:'The finer details.',eyebrow:'TERMS OF SERVICE',paragraphs:['This is an editorial jewelry collection. Photography and finish previews are illustrative; request exact-piece photographs and certification from the concierge before committing to a purchase.', 'Displayed prices are estimates in USD. Platinum and rose-gold selections may change the estimate. Final specifications, stock availability, taxes, sizing, return eligibility and delivery arrangements are confirmed in writing by the atelier.', 'Adding a creation to your private bag or opening WhatsApp does not reserve stock, place a binding order or take payment. A purchase is only finalized after your consultation and agreement to the final invoice.']},
};

export const InfoDialog = ({type,onClose}) => {const info=content[type];return <Modal open onClose={onClose} title={info.title} className="info-modal" testId="info-dialog"><span className="eyebrow">{info.eyebrow}</span><h2 data-testid="info-title">{info.title}</h2>{info.paragraphs.map((p,i)=><p key={i} data-testid={`info-paragraph-${i}`}>{p}</p>)}<a className="text-link" href={consultationLink} target="_blank" rel="noopener noreferrer" data-testid="info-concierge-link">Your concierge is here to help <ArrowUpRight size={15}/></a></Modal>;};

export const MenuDialog = ({onClose,onCategory}) => <Modal open onClose={onClose} title="Explore VELARO" className="menu-modal" testId="menu-dialog"><span className="eyebrow">THE WORLD OF VELARO</span><h2>Extraordinary awaits.</h2>{[['All','All creations'],['Rings','Signature rings'],['Pendants','Necklaces & pendants'],['Earrings','Earrings'],['Bracelets','Bracelets'],['Bridal','Royal bridal suite'],['Men','For him']].map(([key,label])=><a href="#collection" key={key} onClick={()=>{onCategory(key);onClose();}} data-testid={`menu-category-${key.toLowerCase()}`}>{label}<ArrowUpRight size={17}/></a>)}<a href="#maison" onClick={onClose} data-testid="menu-maison">The Maison<ArrowUpRight size={17}/></a><a href="#size-guide" onClick={onClose} data-testid="menu-size-guide">Your perfect fit<ArrowUpRight size={17}/></a></Modal>;